In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

In [2]:
A=pd.read_csv("short_x_data.csv")
B=pd.read_csv("short_x_labels.csv")
C=pd.read_csv("final_test_set.csv")
D=pd.read_csv("final_test_label.csv")
E=pd.read_csv("final_x_train.csv")
F=pd.read_csv("final_y_train.csv")

In [3]:
A=A.values
B=B.values
C=C.values
D=D.values
E=E.values
F=F.values

In [4]:
E.shape

(18914, 500)

In [5]:
B=B.reshape((2500,))

In [6]:
D=D.reshape((2455,))

In [7]:
F=F.reshape((18914,))

In [10]:
rf = RandomForestClassifier()

In [11]:
rf.fit(E,F)

RandomForestClassifier()

In [12]:
rf.score(C,D)

0.9604887983706721

In [34]:
rf.score(E,F)

0.9994184202178281

In [8]:
from keras.layers import Dense,Dropout,Flatten,Embedding
from keras.models import Sequential
from keras.layers import *

Using TensorFlow backend.


In [9]:
model = Sequential([
          Embedding(179999,50,input_length=500),
          GlobalAveragePooling1D(),
          Dense(32,activation = 'relu'),
          Dropout(0.25),
          Dense(1,activation = 'sigmoid')       
])


In [10]:
model.compile('adam','binary_crossentropy',['accuracy'])

In [14]:
#from keras.utils import to_categorical
#F = to_categorical(F)
#D = to_categorical(D)

In [26]:
model.fit(embedding_matrix_train,F)

ValueError: Error when checking input: expected embedding_1_input to have 2 dimensions, but got array with shape (2500, 500, 50)

In [14]:
from sklearn.naive_bayes import MultinomialNB,BernoulliNB,GaussianNB


In [15]:

mnb=MultinomialNB()

In [16]:
mnb.fit(E,F)


MultinomialNB()

In [17]:
mnb.predict(C) 

array([0, 0, 0, ..., 1, 0, 1], dtype=int64)

In [18]:
mnb.predict_proba(C)

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [19]:
mnb.score(A,B)

0.5264

In [20]:
mnb.fit(E,F)


MultinomialNB()

In [21]:
mnb.predict(C)

array([0, 0, 0, ..., 1, 0, 1], dtype=int64)

In [22]:
mnb.score(E,F)

0.6355080892460612

In [23]:
mnb.score(C,D)

0.5173116089613035

# Bernoullis

In [24]:
bnb=BernoulliNB(binarize=0.0)

In [25]:
bnb.fit(A,B)

BernoulliNB()

In [26]:
bnb.predict(C)

array([0, 0, 0, ..., 1, 0, 1], dtype=int64)

In [27]:
bnb.predict_proba(C)

array([[1.00000000e+00, 4.97058638e-21],
       [1.00000000e+00, 2.55885020e-20],
       [9.99999997e-01, 2.51801826e-09],
       ...,
       [7.08420678e-09, 9.99999993e-01],
       [1.00000000e+00, 4.82959467e-17],
       [5.46007590e-31, 1.00000000e+00]])

In [28]:
bnb.score(A,B)


0.4748

In [29]:
bnb.fit(E,F)

BernoulliNB()

In [30]:
bnb.predict(C)

array([0, 0, 0, ..., 1, 0, 1], dtype=int64)

In [31]:
bnb.score(E,F)

0.5455747065665645

In [32]:
bnb.score(C,D)

0.4305498981670061

In [82]:
#CREATING A MODEL IN KERAS
from keras.layers import Embedding,Dense,SimpleRNN
from keras.models import Sequential
model=Sequential()
model.add(Embedding(173977,128))        # 10000 is the vocab_size and 64 is the output dimension i.e. k==embedding size
model.add(SimpleRNN(64))           # 32  is the shape of context vector/ activation vector
model.add(Dense(1,activation="sigmoid"))    # 1 is the number of unit in dense layer

In [83]:

# compile our model 
model.compile(optimizer="Adam",loss="binary_crossentropy",metrics=["acc"])

In [48]:
# Accuracy on test set
model.evaluate(C,D)

2455/2455 [==============================] - 6s 2ms/step


[0.7807504936294012, 0.1604887992143631]

In [49]:
model.evaluate(A,B)

2500/2500 [==============================] - 5s 2ms/step


[0.7796509637832642, 0.1687999963760376]

In [84]:
model.evaluate(E,F)

18914/18914 [==============================] - 43s 2ms/step


[0.6941334757805375, 0.5086179375648499]

In [15]:
model.evaluate(C,D)

2455/2455 [==============================] - 0s 114us/step


[0.6232927930816371, 0.5792260766029358]

In [16]:
import numpy as np

In [21]:
def embedding_output(x):
    maxLen=500
    emb_dim=50
    embedding_out=np.zeros((x.shape[0],maxLen,emb_dim))
    for ix in range(x.shape[0]):
        #x[ix]=x[ix].split()
        for k in range(len(x[ix])):
            try:
                embedding_out[ix][k]=embedding_index[x[ix][k].lower()]
            except:
                embedding_out[ix][k]=np.zeros((50,))
    return embedding_out                

In [22]:
embedding_matrix_train=embedding_output(A)

In [24]:
embedding_matrix_test=embedding_output(C)

In [25]:
print(embedding_matrix_train.shape,embedding_matrix_test.shape)

(2500, 500, 50) (2455, 500, 50)


In [8]:
from keras.layers import Embedding,Dense,SimpleRNN
from keras.models import Sequential


In [9]:
from keras.layers import *

In [ ]:
# Create the model
embedding_vecor_length = 32
model = Sequential()
model.add(Embedding(173977, embedding_vecor_length))
model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())
model.fit(E, F, validation_data=(C, D), epochs=10, batch_size=64)

# Final evaluation of the model
scores = model.evaluate(C,D, verbose=0)
print("Accuracy= %.2f%%" % (scores[1]*100))

# Draw the confusion matrix
y_pred = model.predict_classes(X_test)
plot_cmat(y_test, y_pred)

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, None, 32)          5567264   
_________________________________________________________________
lstm_1 (LSTM)                (None, 100)               53200     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 101       
Total params: 5,620,565
Trainable params: 5,620,565
Non-trainable params: 0
_________________________________________________________________
None


C:\Users\hp\Anaconda3\lib\site-packages\tensorflow_core\python\framework\indexed_slices.py:424: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Train on 18914 samples, validate on 2455 samples
Epoch 1/10
18914/18914 [==============================] - 408s 22ms/step - loss: 0.6691 - accuracy: 0.5495 - val_loss: 0.2628 - val_accuracy: 0.8872
Epoch 2/10
18914/18914 [==============================] - 452s 24ms/step - loss: 0.6103 - accuracy: 0.5922 - val_loss: 0.6951 - val_accuracy: 0.2232
Epoch 3/10
18914/18914 [==============================] - 450s 24ms/step - loss: 0.5728 - accuracy: 0.6118 - val_loss: 0.7585 - val_accuracy: 0.2143
Epoch 4/10
 4544/18914 [======>.......................] - ETA: 5:37 - loss: 0.5418 - accuracy: 0.6309