In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier    

In [2]:
A=pd.read_csv("train_data.csv")
B=pd.read_csv("train_data_labels.csv")
C=pd.read_csv("data_train_test.csv")
D=pd.read_csv("y_test_labels.csv")

In [3]:
A=A.values
B=B.values
C=C.values
D=D.values


In [22]:
rf = RandomForestClassifier()

In [23]:
rf.fit(A,B)

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestClassifier()

In [24]:
A.shape

(8043, 64)

In [25]:
B.shape

(8043, 1)

In [4]:
B=B.reshape((-1,))

In [27]:
B.shape

(8043,)

In [28]:
rf.fit(A,B)

RandomForestClassifier()

In [29]:
rf.score(C,D)

0.19393336648433615

In [37]:
rf.score(A,B)

1.0

In [55]:
rt=RandomForestClassifier(n_estimators=22,criterion="entropy",max_depth=5)

In [56]:
rt.fit(A,B)

RandomForestClassifier(criterion='entropy', max_depth=5, n_estimators=22)

In [57]:
rt.score(A,B)

0.3210244933482531

In [58]:
rt.predict(C)

array([3, 2, 3, ..., 3, 2, 3], dtype=int64)

In [59]:
rt.score(C,D)

0.20387866732968674

# Logistic Regression

In [60]:
from sklearn.linear_model import LogisticRegression

In [61]:
from sklearn.model_selection import cross_val_score

In [63]:
lr=LogisticRegression()

In [64]:
cross_val_score(lr,A,B,cv=5).mean()

0.19209197950582696

# SVM 

In [5]:
from sklearn import svm
svc=svm.SVC()          # by default it is a RBF kernel

In [66]:
svc.fit(A,B)

SVC()

In [67]:
svc.score(A,B)

0.5546437896307348

In [68]:
svc.predict(C)

array([1, 3, 2, ..., 2, 2, 2], dtype=int64)

In [70]:
svc.score(C,D)

0.20586772749875684

In [72]:
svc=svm.SVC(kernel="poly")

In [73]:
svc.fit(A,B)

SVC(kernel='poly')

In [74]:
svc.score(A,B)

0.6856894193708815

In [75]:
svc.predict(C)

array([5, 3, 2, ..., 2, 5, 2], dtype=int64)

In [76]:
svc.score(C,D)

0.19293883639980108

In [5]:
def custom_kernel(x1,x2):
    return np.square(np.dot(x1,x2.T))

In [6]:
svc=svm.SVC(kernel=custom_kernel)

In [6]:
svc.fit(A,B)

SVC()

In [ ]:
svc.score(A,B)

In [ ]:
svc.predict(C)

In [ ]:
svc.score(C,D)

In [31]:
from sklearn.naive_bayes import MultinomialNB,BernoulliNB,GaussianNB


In [32]:
mnb=MultinomialNB()

In [33]:
mnb.fit(A,B)

MultinomialNB()

In [34]:
mnb.score(A,B)

0.20688797712296406

In [35]:
from sklearn.tree import DecisionTreeClassifier
sk_tree=DecisionTreeClassifier(criterion="entropy",max_depth=5)
sk_tree.fit(A,B)
sk_tree.predict(C)
sk_tree.score(C,D)

0.2033814022874192

In [36]:
sk_tree.score(A,B)

0.23349496456546065