In [76]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random

In [77]:
A0=pd.read_csv("complete_politifactdataset.csv")
B0=pd.read_csv("complete_gossipcopdataset.csv")
A1=pd.read_csv("complete_politifactlabels.csv")
B1=pd.read_csv("complete_gossipcoplabels.csv")

In [78]:
print(A0.shape,B0.shape)

(994, 1) (21871, 1)


In [79]:
print(A1.shape,B1.shape)

(994, 1) (21871, 1)


In [80]:
A0.head(n=10)

0
0  BREAKING: First NFL Team Declares Bankruptcy O...
1  Court Orders Obama To Pay $400 Million In Rest...
2  UPDATE: Second Roy Moore Accuser Works For Mic...
3  Oscar Pistorius Attempts To Commit Suicidehttp...
4  Trump Votes For Death Penalty For Being Gayhtt...
5  Putin says: ‘Pope Francis Is Not A Man Of God’...
6  New York Man Wanted For Infecting 240 Men And ...
7  Saudi Arabia to Behead 6 School Girls for Bein...
8  Malia Obama Fired From Cushy Internship At Spa...
9  Target to Discontinue Sale of Holy Biblehttp:/...

In [81]:
import string 
punctuation=string.punctuation

In [82]:
def remove_punc(row):
    text=row.lower()
    text=text.split()
    text=[w for w in text if w.isalpha()]
    text=[w for w in text if w not in punctuation]
    return text

In [83]:
A0.isnull().values.any()

False

In [84]:
A0=A0["0"].apply(remove_punc)

In [85]:
A0.head()

0    [first, nfl, team, declares, bankruptcy, over,...
1         [court, orders, obama, to, pay, million, in]
2    [second, roy, moore, accuser, works, for, mich...
3             [oscar, pistorius, attempts, to, commit]
4      [trump, votes, for, death, penalty, for, being]
Name: 0, dtype: object

In [86]:
from nltk.tokenize import RegexpTokenizer 

In [87]:
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

In [88]:
ps=PorterStemmer()
english_stopwords=set(stopwords.words("english"))

In [89]:
additional_words={'com','http','www','stori','wa','hi','ha','pleas'}

In [90]:
total_stopwords=english_stopwords.union(additional_words)

In [91]:
def proc(row):
    text = [ps.stem(word) for word in row]
    text = [w for w in text if w not in total_stopwords]
    text = [w.encode('ascii', 'ignore').decode('ascii') for w in text]
    return text

In [92]:
A0=A0.apply(proc) 

In [93]:
A0.head()

0        [first, nfl, team, declar, bankruptci, kneel]
1                  [court, order, obama, pay, million]
2    [second, roy, moor, accus, work, michel, obama...
3                   [oscar, pistoriu, attempt, commit]
4                        [trump, vote, death, penalti]
Name: 0, dtype: object

In [94]:
def rejoin(ro):
    joined_text=(" ".join(ro))
    return joined_text

In [95]:
A=A0.apply(rejoin) 

In [96]:
A.head()

0           first nfl team declar bankruptci kneel
1                    court order obama pay million
2    second roy moor accus work michel obama right
3                    oscar pistoriu attempt commit
4                         trump vote death penalti
Name: 0, dtype: object

In [97]:
B0=B0["0"].apply(remove_punc)

In [98]:
B0=B0.apply(proc)

In [99]:
B0=B0.apply(rejoin)

In [100]:
B0.head()

0          teen mom star jenel wed dress avail
1          kyli jenner refus discuss tyga life
2                                        quinn
3                   tri kim butt workout forev
4    celin dion donat concert proce vega shoot
Name: 0, dtype: object

In [101]:
from sklearn.preprocessing import LabelEncoder


In [102]:
le=LabelEncoder()

In [103]:
B1=B1.values
B1=B1.reshape((-1,))

In [104]:
B1=le.fit_transform(B1)

In [105]:
B1

array([1, 1, 1, ..., 0, 0, 0])

In [106]:
A1=A1.values

In [107]:
A1=A1.reshape((-1,))

In [108]:
A1=le.fit_transform(A1)

In [109]:
A1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [35]:
#!pip install simpletransformers 

In [36]:
#from transformers import MobileBertConfig
#from simpletransformers.classification import ClassificationModel
#import sklearn
#import itertools

In [37]:
train_args = {
    'evaluate_during_training': True,
    'logging_steps': 100,
    'num_train_epochs': 2,
    'evaluate_during_training_steps': 100,
    'save_eval_checkpoints': False,
    'train_batch_size': 32,
    'eval_batch_size': 64,
    'overwrite_output_dir': True,
    'fp16': False,
    'wandb_project': "visualization-demo"
}

In [38]:
model_BERT = ClassificationModel('bert', 'bert-base-cased', num_labels=2, use_cuda=True, cuda_device=0, args=train_args)

NameError: name 'ClassificationModel' is not defined

In [ ]:
model_BERT.train_model(train_df_clean, eval_df=eval_df_clean)

In [39]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences


Using TensorFlow backend.


In [110]:
tokenizer = Tokenizer(num_words=10000,char_level=False)
tokenizer.fit_on_texts(A0)
sequences_train = tokenizer.texts_to_sequences(A0)
word_index = tokenizer.word_index
print('Found %s unique tokens in Train.' % len(word_index))
data_train1 = pad_sequences(sequences_train, maxlen=9)
print('Shape of Train data tensor:', data_train1.shape)

Found 2009 unique tokens in Train.
Shape of Train data tensor: (994, 9)


In [111]:
data_train1

array([[   0,    0,    0, ...,  159,  816,  817],
       [   0,    0,    0, ...,    2,   90,   32],
       [   0,  228,  116, ...,  118,    2,   61],
       ...,
       [ 698,   38,   20, ...,  135,  458,  726],
       [   0,    0,    0, ..., 2008, 2009,  797],
       [   0,    0,    0, ...,    0,  786,  422]])

In [112]:
tokenizer = Tokenizer(num_words=10000,char_level=False)
tokenizer.fit_on_texts(B0)
sequences_train = tokenizer.texts_to_sequences(B0)
word_index = tokenizer.word_index
print('Found %s unique tokens in Train.' % len(word_index))
data_train2 = pad_sequences(sequences_train, maxlen=9)
print('Shape of Train data tensor:', data_train2.shape)

Found 9965 unique tokens in Train.
Shape of Train data tensor: (21871, 9)


In [113]:
data_train2

array([[   0,    0,  214, ...,   21,   88, 4123],
       [   0,    0,    0, ...,  926, 1323,  119],
       [   0,    0,    0, ...,    0,    0, 4124],
       ...,
       [   0,    0,    0, ...,  381,  839, 6251],
       [   0,    0,    0, ...,  555,    6,   61],
       [ 318,   85,   33, ...,  115,   16,   85]])

In [114]:
from sklearn.model_selection import train_test_split
x_traina, x_testa, y_traina , y_testa = train_test_split(data_train1,A1,test_size = 0.2)

In [115]:
from sklearn.model_selection import train_test_split
x_trainb, x_testb, y_trainb , y_testb = train_test_split(data_train2,B1,test_size = 0.2)

In [116]:
x_traina.shape

(795, 9)

In [117]:
x_traina=pd.DataFrame(x_traina)

In [118]:
x_traina.to_csv("x_traina.csv",index=False)

In [119]:
x_testa=pd.DataFrame(x_testa)
x_testa.to_csv("x_testa.csv",index=False)

In [120]:
y_testa=pd.DataFrame(y_testa)
y_testa.to_csv("y_testa.csv",index=False)

In [121]:
y_traina=pd.DataFrame(y_traina)
y_traina.to_csv("y_traina.csv",index=False)

In [122]:
y_traina

0
0    1
1    1
2    1
3    0
4    0
..  ..
790  0
791  1
792  1
793  1
794  1

[795 rows x 1 columns]

In [123]:
x_testb=pd.DataFrame(x_testb)
x_testb.to_csv("x_testb.csv",index=False)

In [124]:
x_trainb=pd.DataFrame(x_trainb)
x_trainb.to_csv("x_trainb.csv",index=False)

In [125]:
y_testb=pd.DataFrame(y_testb)
y_testb.to_csv("y_testb.csv",index=False)

In [126]:
y_trainb=pd.DataFrame(y_trainb)
y_trainb.to_csv("y_trainb.csv",index=False)

In [127]:

MAX_NUM_WORDS = 10000
MAX_SEQUENCE_LENGTH = 9

In [58]:
from keras.utils import to_categorical
labels = to_categorical(np.asarray(A1))
print(labels.shape)

(994, 2)


In [59]:
embeddings_index = {}
f = open("glove.6B.50d.txt",encoding="utf-8")
for line in f:
    values = line.split(' ')
    word = values[0] ## The first entry is the word
    coefs = np.asarray(values[1:], dtype='float32') ## These are the vecotrs representing the embedding for the word
    embeddings_index[word] = coefs
f.close()

print('GloVe data loaded')

GloVe data loaded


In [60]:
## More code adapted from the keras reference (https://github.com/keras-team/keras/blob/master/examples/pretrained_word_embeddings.py)
# prepare embedding matrix 
from keras.layers import Embedding
from keras.initializers import Constant

## EMBEDDING_DIM =  ## seems to need to match the embeddings_index dimension
EMBEDDING_DIM = embeddings_index.get('a').shape[0]
num_words = min(MAX_NUM_WORDS, len(word_index)) + 1
embedding_matrix = np.zeros((num_words, EMBEDDING_DIM))
for word, i in word_index.items():
    if i > MAX_NUM_WORDS:
        continue
    embedding_vector = embeddings_index.get(word) ## This references the loaded embeddings dictionary
    if embedding_vector is not None:
        # words not found in embedding index will be all-zeros.
        embedding_matrix[i] = embedding_vector

# load pre-trained word embeddings into an Embedding layer
# note that we set trainable = False so as to keep the embeddings fixed
embedding_layer = Embedding(num_words,
                            EMBEDDING_DIM,
                            embeddings_initializer=Constant(embedding_matrix),
                            input_length=MAX_SEQUENCE_LENGTH,
                            trainable=False)

In [61]:
def embedding_output(data):
    emb_dim=50
    max_len=9
    emb=np.zeros((data.shape[0],max_len,emb_dim))
    print(emb.shape)
    for i in range(data.shape[0]):
        
        for j in range(9):
            try:
                emb[i][j]=embeddings_index[data[i][j].lower()]
            except:
                emb[i][j]=np.zeros((50,))
        return emb

In [62]:
e=embedding_output(data_train1)

(994, 9, 50)


In [63]:
texts=np.array(data_train1)

In [64]:
## Code from: https://medium.com/@sabber/classifying-yelp-review-comments-using-cnn-lstm-and-pre-trained-glove-word-embeddings-part-3-53fcea9a17fa
## To create and visualize a model

from keras.models import Sequential
from keras.layers import Dense, Flatten, LSTM, Conv1D, MaxPooling1D, Dropout, Activation

model = Sequential()

model.add(LSTM(64,input_shape=(9,50),return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(64,input_shape=(9,50),return_sequences=False))
model.add(Dropout(0.2))

model.add(Dense(2, activation='sigmoid'))


In [65]:

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [66]:
hist=model.fit(e,labels,epochs=50,batch_size=64,shuffle=True,validation_split=0.1)

Train on 894 samples, validate on 100 samples
Epoch 1/50
894/894 [==============================] - 2s 2ms/step - loss: 0.6929 - accuracy: 0.5112 - val_loss: 0.6631 - val_accuracy: 1.0000
Epoch 2/50
894/894 [==============================] - 0s 419us/step - loss: 0.6924 - accuracy: 0.5224 - val_loss: 0.6467 - val_accuracy: 1.0000
Epoch 3/50
894/894 [==============================] - 0s 435us/step - loss: 0.6924 - accuracy: 0.5224 - val_loss: 0.6589 - val_accuracy: 1.0000
Epoch 4/50
894/894 [==============================] - 0s 415us/step - loss: 0.6924 - accuracy: 0.5224 - val_loss: 0.6576 - val_accuracy: 1.0000
Epoch 5/50
894/894 [==============================] - 0s 411us/step - loss: 0.6922 - accuracy: 0.5224 - val_loss: 0.6521 - val_accuracy: 1.0000
Epoch 6/50
894/894 [==============================] - 0s 424us/step - loss: 0.6921 - accuracy: 0.5224 - val_loss: 0.6412 - val_accuracy: 1.0000
Epoch 7/50
894/894 [==============================] - 0s 427us/step - loss: 0.6922 - accurac

KeyboardInterrupt: 

In [67]:
from keras.utils import to_categorical
labelss= to_categorical(np.asarray(B1))
print(labelss.shape)

(21871, 2)


In [68]:
F=embedding_output(data_train2)

(21871, 9, 50)


In [69]:
textss=np.array(data_train2)

In [70]:
hist=model.fit(F,labelss,epochs=50,batch_size=64,shuffle=False,validation_split=0.1)

Train on 19683 samples, validate on 2188 samples
Epoch 1/50
19683/19683 [==============================] - 9s 454us/step - loss: 0.4932 - accuracy: 0.8861 - val_loss: 0.4867 - val_accuracy: 1.0000
Epoch 2/50
19683/19683 [==============================] - 9s 453us/step - loss: 0.4441 - accuracy: 0.8060 - val_loss: 0.1104 - val_accuracy: 1.0000
Epoch 3/50
19683/19683 [==============================] - 9s 457us/step - loss: 0.5971 - accuracy: 0.7522 - val_loss: 0.9186 - val_accuracy: 0.0000e+00
Epoch 4/50
19683/19683 [==============================] - 9s 456us/step - loss: 0.5034 - accuracy: 0.8537 - val_loss: 1.1232 - val_accuracy: 0.0000e+00
Epoch 5/50
19683/19683 [==============================] - 9s 458us/step - loss: 0.4738 - accuracy: 0.8537 - val_loss: 1.2712 - val_accuracy: 0.0000e+00
Epoch 6/50
19683/19683 [==============================] - 9s 458us/step - loss: 0.4597 - accuracy: 0.8537 - val_loss: 1.3572 - val_accuracy: 0.0000e+00
Epoch 7/50
19683/19683 [=======================

KeyboardInterrupt: 

# Attention Layer Classifier

In [68]:

from keras.layers import Layer
import keras.backend as K

In [69]:
class attention(Layer):
    def __init__(self,**kwargs):
        super(attention,self).__init__(**kwargs)

    def build(self,input_shape):
        self.W=self.add_weight(name="att_weight",shape=(input_shape[-1],1),initializer="normal")
        self.b=self.add_weight(name="att_bias",shape=(input_shape[1],1),initializer="zeros")        
        super(attention, self).build(input_shape)

    def call(self,x):
        et=K.squeeze(K.tanh(K.dot(x,self.W)+self.b),axis=-1)
        at=K.softmax(et)
        at=K.expand_dims(at,axis=-1)
        output=x*at
        return K.sum(output,axis=1)

    def compute_output_shape(self,input_shape):
        return (input_shape[0],input_shape[-1])

    def get_config(self):
        return super(attention,self).get_config()

In [70]:
from numpy import newaxis
from keras.layers import Lambda

In [71]:
def axis(a):
    a = a[ :, :, newaxis]
    return a


In [72]:
word_vector_matrix = np.zeros((10000, 50))
unavailable = 0

for word, index in tokenizer.word_index.items():
    vector = embeddings_index.get(word)
    if vector is not None:
        word_vector_matrix[index] = vector
    else:
        unavailable = unavailable + 1
        #print(word)

In [73]:
import keras
sequence_input = keras.layers.Input(shape=(9,), dtype='int32')
x = keras.layers.Embedding(10000, 50, input_length = 9, weights = [word_vector_matrix], trainable = False)(sequence_input)

In [74]:
att_out=attention()(x)


In [75]:
x = Lambda(axis)(att_out)

In [76]:
y = keras.layers.Conv1D(96,(11),strides = 2,activation = 'relu',input_shape=(100,1))(x)
y = keras.layers.MaxPooling1D(3,2)(y)

y = keras.layers.Conv1D(256,5,padding = 'same',activation = 'relu')(y)
y = keras.layers.MaxPooling1D(3,2)(y)

y = keras.layers.Conv1D(384,3,padding='same',activation= 'relu')(y)
y = keras.layers.Conv1D(384,3,padding='same',activation= 'relu')(y)
y = keras.layers.Conv1D(256,3,padding='same',activation= 'relu')(y)
y = keras.layers.MaxPooling1D(3,2)(y)

y = keras.layers.Flatten()(y)
y = keras.layers.Dense(128, activation = 'relu')(y)
y = keras.layers.Dense(256, activation = 'relu')(y)
y = keras.layers.Dense(64, activation = 'relu')(y)


In [77]:

output=keras.layers.Dense(2,activation='sigmoid',trainable=True)(y)

In [78]:
model=keras.Model(inputs = sequence_input,outputs = output)
model.summary()


Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 9)                 0         
_________________________________________________________________
embedding_2 (Embedding)      (None, 9, 50)             500000    
_________________________________________________________________
attention_1 (attention)      (None, 50)                59        
_________________________________________________________________
lambda_1 (Lambda)            (None, 50, 1)             0         
_________________________________________________________________
conv1d_1 (Conv1D)            (None, 20, 96)            1152      
_________________________________________________________________
max_pooling1d_1 (MaxPooling1 (None, 9, 96)             0         
_________________________________________________________________
conv1d_2 (Conv1D)            (None, 9, 256)            1231

In [79]:
adam = keras.optimizers.Adadelta(learning_rate=0.0001, rho=0.95)

In [80]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [81]:
epochs = 20
batch_size = 25

history = model.fit(data_train1, labels, epochs=epochs, batch_size=batch_size,validation_split = 0.1)

Train on 894 samples, validate on 100 samples
Epoch 1/20
894/894 [==============================] - 2s 3ms/step - loss: 0.6864 - accuracy: 0.5453 - val_loss: 0.5369 - val_accuracy: 1.0000
Epoch 2/20
894/894 [==============================] - 2s 2ms/step - loss: 0.6267 - accuracy: 0.6376 - val_loss: 0.5491 - val_accuracy: 0.7300
Epoch 3/20
894/894 [==============================] - 2s 2ms/step - loss: 0.6003 - accuracy: 0.7058 - val_loss: 0.3479 - val_accuracy: 0.8300
Epoch 4/20
894/894 [==============================] - 1s 2ms/step - loss: 0.5955 - accuracy: 0.6857 - val_loss: 0.8065 - val_accuracy: 0.3200
Epoch 5/20
894/894 [==============================] - 2s 2ms/step - loss: 0.5713 - accuracy: 0.7013 - val_loss: 0.4432 - val_accuracy: 0.7600
Epoch 6/20
894/894 [==============================] - 2s 2ms/step - loss: 0.5578 - accuracy: 0.7438 - val_loss: 0.7115 - val_accuracy: 0.5700
Epoch 7/20
894/894 [==============================] - 2s 2ms/step - loss: 0.5322 - accuracy: 0.7450 - 

In [71]:
epochs = 20
batch_size = 25

history = model.fit(data_train2, labelss, epochs=epochs, batch_size=batch_size,validation_split = 0.3)

# Naive Bayes Classifier

In [128]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB

In [129]:
mnb=MultinomialNB()

In [130]:
y_traina=y_traina.values
y_traina=y_traina.reshape((-1,))
y_trainb=y_trainb.values
y_trainb=y_trainb.reshape((-1,))

In [131]:
mnb.fit(x_traina,y_traina)

MultinomialNB()

In [132]:
A=mnb.predict(x_testa)

In [133]:
y_testa=y_testa.values
y_testa=y_testa.reshape((-1,))
y_testb=y_testb.values
y_testb=y_testb.reshape((-1,))


In [134]:
mnb.score(x_testa,y_testa)

0.7185929648241206

In [135]:
mnb.score(x_traina,y_traina)

0.6691823899371069

In [136]:
mnb.fit(x_trainb,y_trainb)

MultinomialNB()

In [137]:
mnb.predict(x_testb)

array([1, 0, 1, ..., 0, 1, 1])

In [138]:
mnb.score(x_testb,y_testb)

0.4889142857142857

In [139]:
bnb=BernoulliNB()
bnb.fit(x_traina,y_traina)

BernoulliNB()

In [140]:
bnb.score(x_traina,y_traina)

0.70062893081761

In [141]:
bnb.predict(x_testa)

array([1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0])

In [142]:
bnb.score(x_testa,y_testa)

0.678391959798995

In [144]:
bnb.fit(x_trainb,y_trainb)

BernoulliNB()

In [145]:
bnb.score(x_trainb,y_trainb)

0.7692043895747599

In [146]:
bnb.predict(x_testb)

array([1, 1, 1, ..., 1, 1, 1])

In [147]:
bnb.score(x_testb,y_testb)

0.7648

# USING ATTENTION LAYER

In [5]:
from keras.layers import Layer
import keras.backend as K

Using TensorFlow backend.


In [6]:
word_vector_matrix

NameError: name 'word_vector_matrix' is not defined

In [7]:
class attention(Layer):
    def __init__(self,**kwargs):
        super(attention,self).__init__(**kwargs)

    def build(self,input_shape):
        self.W=self.add_weight(name="att_weight",shape=(input_shape[-1],1),initializer="normal")
        self.b=self.add_weight(name="att_bias",shape=(input_shape[1],1),initializer="zeros")        
        super(attention, self).build(input_shape)

    def call(self,x):
        et=K.squeeze(K.tanh(K.dot(x,self.W)+self.b),axis=-1)
        at=K.softmax(et)
        at=K.expand_dims(at,axis=-1)
        output=x*at
        return K.sum(output,axis=1)

    def compute_output_shape(self,input_shape):
        return (input_shape[0],input_shape[-1])

    def get_config(self):
        return super(attention,self).get_config()

In [8]:
from numpy import newaxis
from keras.layers import Lambda

In [11]:
def axis(a):
    a = a[ :, :, newaxis]
    return a


In [14]:
import numpy as np
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
vocab_size=10000
word_vector_matrix = np.zeros((vocab_size, 50))
unavailable = 0

for word, index in tokenizer.word_index.items():
    vector = self_vectors.get(word)
    if vector is not None:
        word_vector_matrix[index] = vector
    else:
        unavailable = unavailable + 1
        print(word)

NameError: name 'tokenizer' is not defined

In [10]:
import keras
sequence_input = keras.layers.Input(shape=(500,), dtype='int32')
x = keras.layers.Embedding(20000, 50, input_length = 500, weights = [word_vector_matrix], trainable = False)(sequence_input)

NameError: name 'word_vector_matrix' is not defined